### ISSUE TITLE
Ruby 3.0 support

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2453]
We plan to work on Ruby 3.0 support for the next release, TruffleRuby/GraalVM 22.0.

Any help is appreciated whether it is:
* implementing one of the Ruby 3 changes in TruffleRuby, and ensuring it is tested in specs or MRI tests and otherwise add specs
* adding specs for Ruby 3 changes, which is best done in ruby/spec directly, see https://github.com/ruby/spec/issues/823

See this comment: https://github.com/oracle/truffleruby/issues/2453#issuecomment-938185003 for finding good getting-started issues.

See https://github.com/oracle/truffleruby/blob/3e03bed224076c2c301a2490a052568a2d013cfe/doc/contributor/workflow.md#running-specs-for-ruby-30-features for how to run specs for 3.0.

# Full list of changes for Ruby 3.0.0

NOTE: https://rubyreferences.github.io/rubychanges/3.0.html gives more details for many features and changes.
From https://github.com/ruby/ruby/blob/master/doc/NEWS-3.0.0.md and https://github.com/ruby/spec/issues/823:

This document is a list of user visible feature changes
since the **2.7.0** release, except for bug fixes.

Note that each entry is kept to a minimum, see links for details.

- [x] @eregon Initial import of CRuby 3.0 sources

## Language changes

See https://github.com/jruby/jruby/issues/6880 regarding parser changes.

- [x] @eregon @chrisseaton @wildmaples Keyword arguments are now separated from positional arguments.
  Code that resulted in deprecation warnings in Ruby 2.7 will now
  result in ArgumentError or different behavior. [[Feature #14183]]

- [x] @eregon Procs accepting a single rest argument and keywords are no longer
  subject to autosplatting.  This now matches the behavior of Procs
  accepting a single rest argument and no keywords.
  [[Feature #16166]]

    ```ruby
    pr = proc{|*a, **kw| [a, kw]}

    pr.call([1])
    # 2.7 => [[1], {}]
    # 3.0 => [[[1]], {}]

    pr.call([1, {a: 1}])
    # 2.7 => [[1], {:a=>1}] # and deprecation warning
    # 3.0 => [[[1, {:a=>1}]], {}]
    ```

- [x] [parser, hard] Arguments forwarding (`...`) now supports leading arguments.
  [[Feature #16378]]

    ```ruby
    def method_missing(meth, ...)
      send(:"do_#{meth}", ...)
    end
    ```

- [ ] @razetime [parser, hard] Pattern matching (`case/in`) is no longer experimental. [[Feature #17260]]

- [ ] @razetime [parser, hard] One-line pattern matching is redesigned.  [EXPERIMENTAL]

    * `=>` is added. It can be used like a rightward assignment.
      [[Feature #17260]]

        ```ruby
        0 => a
        p a #=> 0

        {b: 0, c: 1} => {b:}
        p b #=> 0
        ```

    * `in` is changed to return `true` or `false`. [[Feature #17371]]

        ```ruby
        # version 3.0
        0 in 1 #=> false

        # version 2.7
        0 in 1 #=> raise NoMatchingPatternError
        ```

- [ ] @razetime [parser, hard] Find-pattern is added.  [EXPERIMENTAL]
  [[Feature #16828]]

    ```ruby
    case ["a", 1, "b", "c", 2, "d", "e", "f", 3]
    in [*pre, String => x, String => y, *post]
      p pre  #=> ["a", 1]
      p x    #=> "b"
      p y    #=> "c"
      p post #=> [2, "d", "e", "f", 3]
    end
    ```

- [ ] [parser, hard] Endless method definition is added.  [EXPERIMENTAL]
  [[Feature #16746]]

    ```ruby
    def square(x) = x * x
    ```

- [x] [easy, undo some of #2304] @bjfish Interpolated String literals are no longer frozen when
  `# frozen-string-literal: true` is used. [[Feature #17104]]

- [ ] [translator, medium] Magic comment `shareable_constant_value` added to freeze constants.
  See {Magic Comments}[rdoc-ref:doc/syntax/comments.rdoc@Magic+Comments] for more details.
  [[Feature #17273]]

- [x] [already the case] Deprecation warnings are no longer shown by default (since Ruby 2.7.2).
  Turn them on with `-W:deprecated` (or with `-w` to show other warnings too).
  [[Feature #16345]]

- [x] @bjfish [cleanup, easy] `$SAFE` and `$KCODE` are now normal global variables with no special behavior.
  C-API methods related to `$SAFE` have been removed.
  [[Feature #16131]] [[Feature #17136]]

- [x] @Strech [medium] yield in singleton class definitions in methods is now a SyntaxError
  instead of a warning. yield in a class definition outside of a method
  is now a SyntaxError instead of a LocalJumpError.  [[Feature #15575]]

- [ ] @Strech [medium] When a class variable is overtaken by the same definition in an
  ancestor class/module, a RuntimeError is now raised (previously,
  it only issued a warning in verbose mode). 
  [[Bug #14541]]

- [x] [medium] @bjfish Accessing a class variable from the toplevel scope is now a RuntimeError.
  [[Bug #14541]]

- [x] [easy] Assigning to a numbered parameter is now a SyntaxError instead of
  a warning.

### `--help` option

- [x] [launcher, medium] @Strech When the environment variable `RUBY_PAGER` or `PAGER` is present and has
a non-empty value, and the standard input and output are tty, the `--help`
option shows the help message via the pager designated by the value.
[[Feature #16754]]

### `--backtrace-limit` option

- [x] @bjfish [medium] The `--backtrace-limit` option limits the maximum length of a backtrace.
[[Feature #8661]]

## Core classes updates

Outstanding ones only.

Array

- [x] [easy, ruby-only] @Strech #2510 The following methods now return Array instances instead of
  subclass instances when called on subclass instances:
  [[Bug #6087]]

    * Array#drop
    * Array#drop_while
    * Array#flatten
    * Array#slice!
    * Array#slice / Array#[]
    * Array#take
    * Array#take_while
    * Array#uniq
    * Array#*

- [x] [medium, ruby-only with one call from java] @ccocchi https://github.com/oracle/truffleruby/pull/2526 Can be sliced with Enumerator::ArithmeticSequence

    ```ruby
    dirty_data = ['--', 'data1', '--', 'data2', '--', 'data3']
    dirty_data[(1..).step(2)] # take each second element
    # => ["data1", "data2", "data3"]
    ```

Binding

- [x] @aardvark179 [easy, might be already the case] Binding#eval when called with one argument will use `"(eval)"`
  for `__FILE__` and `1` for `__LINE__` in the evaluated code.
  [[Bug #4352]] [[Bug #17419]]

ConditionVariable

- [ ] @aardvark179 [hard] ConditionVariable#wait may now invoke the `block`/`unblock` scheduler
  hooks in a non-blocking context. [[Feature #16786]]

Dir

- [x] [probably already the case, need to check] @Strech Dir.glob and Dir.[] now sort the results by default, and
  accept the `sort:` keyword option.  [[Feature #8709]]

ENV

- [x] [easy, pure ruby] ENV.except has been added, which returns a hash excluding the
  given keys and their values.  [[Feature #15822]]

- [x] Windows: Read ENV names and values as UTF-8 encoded Strings
  [[Feature #12650]]

Encoding

- [ ] [hard, jcodings] Added new encoding IBM720.  [[Feature #16233]]

- [x] Changed default for Encoding.default_external to UTF-8 on Windows
  [[Feature #16604]]

Fiber

- [x] [easy] @aardvark179 Fiber.new(blocking: true/false) allows you to create non-blocking
  execution contexts. [[Feature #16786]]

- [x] [easy] @aardvark179 Fiber#blocking? tells whether the fiber is non-blocking. [[Feature #16786]]

- [ ] [medium] @eregon Fiber#backtrace and Fiber#backtrace_locations provide per-fiber backtrace.
  [[Feature #16815]]

- [x] @bjfish The limitation of Fiber#transfer is relaxed. [[Bug #17221]]

GC

- [x] @bjfish [easy, pure ruby, just keep the state no effect] GC.auto_compact= and GC.auto_compact have been added to control
  when compaction runs.  Setting `auto_compact=` to `true` will cause
  compaction to occur during major collections.  At the moment,
  compaction adds significant overhead to major collections, so please
  test first!  [[Feature #17176]]

Hash

- [x] [easy, pure ruby] @ccocchi #2464 Hash#transform_keys and Hash#transform_keys! now accept a hash that maps
  keys to new keys.  [[Feature #16274]]

- [x] [easy, pure ruby] @wildmaples #2463 Hash#except has been added, which returns a hash excluding the
  given keys and their values.  [[Feature #15822]]

IO

- [ ] [hard, need to check side effects] @aardvark179 IO#nonblock? now defaults to `true`. [[Feature #16786]]

- [ ] [hard] @aardvark179 IO#wait_readable, IO#wait_writable, IO#read, IO#write and other
  related methods (e.g. IO#puts, IO#gets) may invoke the scheduler hook
  `#io_wait(io, events, timeout)` in a non-blocking execution context.
  [[Feature #16786]]

Kernel

- [x] [medium, java] @andrykonchin Kernel#clone when called with the `freeze: false` keyword will call
  `#initialize_clone` with the `freeze: false` keyword.
  [[Bug #14266]]

- [x] [medium, java] @andrykonchin Kernel#clone when called with the `freeze: true` keyword will call
  `#initialize_clone` with the `freeze: true` keyword, and will
  return a frozen copy even if the receiver is unfrozen.
  [[Feature #16175]]

- [x] @aardvark179 [easy, might be already the case] Kernel#eval when called with two arguments will use `"(eval)"`
  for `__FILE__` and `1` for `__LINE__` in the evaluated code.
  [[Bug #4352]]

- [x] [easy] Kernel#lambda now warns if called without a literal block.
  [[Feature #15973]]

- [ ] [hard] @aardvark179 Kernel.sleep invokes the scheduler hook `#kernel_sleep(...)` in a
  non-blocking execution context. [[Feature #16786]]

Module

- [ ] [hard] @bjfish Module#include and Module#prepend now affect classes and modules
  that have already included or prepended the receiver, mirroring the
  behavior if the arguments were included in the receiver before
  the other modules and classes included or prepended the receiver.
  [[Feature #9573]]

    ```ruby
    class C; end
    module M1; end
    module M2; end
    C.include M1
    M1.include M2
    p C.ancestors #=> [C, M1, M2, Object, Kernel, BasicObject]
    ```

- [x] @bjfish [medium, java] Module#public, Module#protected, Module#private, Module#public_class_method,
  Module#private_class_method, toplevel "private" and "public" methods
  now accept single array argument with a list of method names. [[Feature #17314]]

- [x] [medium, java] @gogainda #2498 Module#attr_accessor, Module#attr_reader, Module#attr_writer and Module#attr
  methods now return an array of defined method names as symbols.
  [[Feature #17314]]

- [x] [easy] @gogainda Module#alias_method now returns the defined alias as a symbol.
  [[Feature #17314]]

Mutex

- [x] [already the case] `Mutex` is now acquired per-`Fiber` instead of per-`Thread`. This change
  should be compatible for essentially all usages and avoids blocking when
  using a scheduler. [[Feature #16792]]

Proc

- [x] [medium] @bjfish Proc#== and Proc#eql? are now defined and will return true for
  separate Proc instances if the procs were created from the same block.
  [[Feature #14267]]

Queue / SizedQueue

- [ ] [hard] @aardvark179 Queue#pop, SizedQueue#push and related methods may now invoke the
  `block`/`unblock` scheduler hooks in a non-blocking context.
  [[Feature #16786]]

Ractor

- [x] [will add later since experimental & unstable in CRuby 3.0] New class added to enable parallel execution. See rdoc-ref:ractor.md for
  more details.

Random

- [x] [easy, pure ruby] @eregon `Random::DEFAULT` now refers to the `Random` class instead of being a `Random` instance,
  so it can work with `Ractor`.
  [[Feature #17322]]

- [x] [easy, pure ruby] @eregon `Random::DEFAULT` is deprecated since its value is now confusing and it is no longer global,
  use `Kernel.rand`/`Random.rand` directly, or create a `Random` instance with `Random.new` instead.
  [[Feature #17351]]

String

- [x] @bjfish [easy] The following methods now return or yield String instances
  instead of subclass instances when called on subclass instances:
  [[Bug #10845]]

    * String#*
    * String#capitalize
    * String#center
    * String#chomp
    * String#chop
    * String#delete
    * String#delete_prefix
    * String#delete_suffix
    * String#downcase
    * String#dump
    * String#each_char
    * String#each_line
    * String#gsub
    * String#ljust
    * String#lstrip
    * String#partition
    * String#reverse
    * String#rjust
    * String#rpartition
    * String#rstrip
    * String#scrub
    * String#slice!
    * String#slice / String#[]
    * String#split
    * String#squeeze
    * String#strip
    * String#sub
    * String#succ / String#next
    * String#swapcase
    * String#tr
    * String#tr_s
    * String#upcase

- [x] @bjfish [easy] The following methods now return or yield String instances
  instead of subclass instances when called on subclass instances:
  [[Bug #10845]]
    * String#each_grapheme_cluster
    * String#scan

Symbol

- [x] [might already be the case, easy] Symbol#to_proc now returns a lambda Proc.  [[Feature #16260]]

- [x] @bjfish [easy, java] Symbol#name has been added, which returns the name of the symbol
  if it is named.  The returned string is frozen.  [[Feature #16150]]

Fiber

- [ ] @aardvark179 [hard] Introduce Fiber.set_scheduler for intercepting blocking operations and
  Fiber.scheduler for accessing the current scheduler. See
  rdoc-ref:fiber.md for more details about what operations are supported and
  how to implement the scheduler hooks. [[Feature #16786]]

- [x] @aardvark179 [hard] Fiber.blocking? tells whether the current execution context is
  blocking. [[Feature #16786]]

- [ ] @aardvark179 [hard] Thread#join invokes the scheduler hooks `block`/`unblock` in a
  non-blocking execution context. [[Feature #16786]]

Thread

- [x] @bjfish [easy, just noop there is no deadlock detection] Thread.ignore_deadlock accessor has been added for disabling the
  default deadlock detection, allowing the use of signal handlers to
  break deadlock. [[Bug #13768]]

Warning

- [x] [should already be the case, easy] @Strech https://github.com/oracle/truffleruby/pull/2533 Warning#warn now supports a category keyword argument.
  [[Feature #17122]]

## Stdlib updates

Set

- [x] SortedSet has been removed for dependency and performance reasons.

- [x] Set#join is added as a shorthand for `.to_a.join`.

- [x] Set#<=> is added.

Socket

- [ ] [hard] Add :connect_timeout to TCPSocket.new [[Feature #17187]]

## Compatibility issues

Excluding feature bug fixes.

- [x] [done for Regexp, todo for Range, medium] @tomstuart @MattAlp Regexp literals and all Range objects are frozen. [[Feature #8948]] [[Feature #16377]] [[Feature #15504]]

    ```ruby
    /foo/.frozen? #=> true
    (42...).frozen? # => true
    ```

- [x] Embed Range literals in the AST https://github.com/oracle/truffleruby/issues/2622

- [x] [medium] @bjfish EXPERIMENTAL: Hash#each consistently yields a 2-element array. [[Bug #12706]]

    * Now `{ a: 1 }.each(&->(k, v) { })` raises an ArgumentError
      due to lambda's arity check.

- [x] [medium] https://github.com/oracle/truffleruby/pull/2532 When writing to STDOUT redirected to a closed pipe, no broken pipe
  error message will be shown now.  [[Feature #14413]]

- [x] [easy, pure ruby] `TRUE`/`FALSE`/`NIL` constants are no longer defined.

- [x] @bjfish [easy, pure ruby] Integer#zero? overrides Numeric#zero? for optimization.  [[Misc #16961]]

- [x] @bjfish [medium] Enumerable#grep and Enumerable#grep_v when passed a Regexp and no block no longer modify
  Regexp.last_match. [[Bug #17030]]

- [x] Requiring 'open-uri' no longer redefines `Kernel#open`.
  Call `URI.open` directly or `use URI#open` instead. [[Misc #15893]]

- [x] SortedSet has been removed for dependency and performance reasons.

## Stdlib compatibility issues

- [x] @eregon Default gems

    * The following libraries are promoted to default gems from stdlib.

        * English
        * abbrev
        * base64
        * drb
        * debug
        * erb
        * find
        * net-ftp
        * net-http
        * net-imap
        * net-protocol
        * open-uri
        * optparse
        * pp
        * prettyprint
        * resolv-replace
        * resolv
        * rinda
        * set
        * securerandom
        * shellwords
        * tempfile
        * tmpdir
        * time
        * tsort
        * un
        * weakref

    * The following extensions are promoted to default gems from stdlib.

        * digest
        * io-nonblock
        * io-wait
        * nkf
        * pathname
        * syslog
        * win32ole

- [x] @eregon Bundled gems

    * net-telnet and xmlrpc have been removed from the bundled gems.
      If you are interested in maintaining them, please comment on
      your plan to https://github.com/ruby/xmlrpc
      or https://github.com/ruby/net-telnet.

- [x] @eregon SDBM has been removed from the Ruby standard library. [[Bug #8446]]

    * The issues of sdbm will be handled at https://github.com/ruby/sdbm

- [x] @eregon WEBrick has been removed from the Ruby standard library. [[Feature #17303]]

    * The issues of WEBrick will be handled at https://github.com/ruby/webrick

## C API updates

- [x] @eregon C API functions related to `$SAFE` have been removed.
  [[Feature #16131]]

- [x] @eregon C API header file `ruby/ruby.h` was split. [[GH-2991]]

    This should have no impact on extension libraries,
    but users might experience slow compilations.

- [ ] @eregon Memory view interface [EXPERIMENTAL]

    * The memory view interface is a C-API set to exchange a raw memory area,
      such as a numeric array or a bitmap image, between extension libraries.
      The extension libraries can share also the metadata of the memory area
      that consists of the shape, the element format, and so on.
      Using these kinds of metadata, the extension libraries can share even
      a multidimensional array appropriately.
      This feature is designed by referring to Python's buffer protocol.
      [[Feature #13767]] [[Feature #14722]]

- [x] [will add later since experimental & unstable in CRuby 3.0] Ractor related C APIs are introduced (experimental) in "include/ruby/ractor.h".

- [x] @eregon  `rb_keyword_given_p()` was added to find if kwargs were passed from Ruby to C.

## Implementation improvements

- [x] [already the case](https://medium.com/graalvm/precise-method-and-constant-invalidation-in-truffleruby-4dd56c6bac1a) New method cache mechanism for Ractor. [[Feature #16614]]

    * Inline method caches pointed from ISeq can be accessed by multiple Ractors
      in parallel and synchronization is needed even for method caches. However,
      such synchronization can be overhead so introducing new inline method cache
      mechanisms, (1) Disposable inline method cache (2) per-Class method cache
      and (3) new invalidation mechanism. (1) can avoid per-method call
      synchronization because it only uses atomic operations.
      See the ticket for more details.

- [x] @eregon The number of hashes allocated when using a keyword splat in
  a method call has been reduced to a maximum of 1, and passing
  a keyword splat to a method that accepts specific keywords
  does not allocate a hash.

- [x] [already the case, all `super` are optimized] `super` is optimized when the same type of method is called in the previous call
  if it's not refinements or an attr reader or writer.

## Miscellaneous changes

- [x] @eregon Methods using `ruby2_keywords` will no longer keep empty keyword
  splats, those are now removed just as they are for methods not
  using `ruby2_keywords`.

- [x] [already the case] When an exception is caught in the default handler, the error
  message and backtrace are printed in order from the innermost.
  [[Feature #8661]]

- [x] [easy, cleanup] Accessing an uninitialized instance variable no longer emits a
  warning in verbose mode. [[Feature #17055]]

[Bug #4352]:      https://bugs.ruby-lang.org/issues/4352
[Bug #6087]:      https://bugs.ruby-lang.org/issues/6087
[Bug #8382]:      https://bugs.ruby-lang.org/issues/8382
[Bug #8446]:      https://bugs.ruby-lang.org/issues/8446
[Feature #8661]:  https://bugs.ruby-lang.org/issues/8661
[Feature #8709]:  https://bugs.ruby-lang.org/issues/8709
[Feature #8948]:  https://bugs.ruby-lang.org/issues/8948
[Feature #9573]:  https://bugs.ruby-lang.org/issues/9573
[Bug #10845]:     https://bugs.ruby-lang.org/issues/10845
[Bug #12136]:     https://bugs.ruby-lang.org/issues/12136
[Feature #12650]: https://bugs.ruby-lang.org/issues/12650
[Bug #12706]:     https://bugs.ruby-lang.org/issues/12706
[Feature #13767]: https://bugs.ruby-lang.org/issues/13767
[Bug #13768]:     https://bugs.ruby-lang.org/issues/13768
[Feature #14183]: https://bugs.ruby-lang.org/issues/14183
[Bug #14266]:     https://bugs.ruby-lang.org/issues/14266
[Feature #14267]: https://bugs.ruby-lang.org/issues/14267
[Feature #14413]: https://bugs.ruby-lang.org/issues/14413
[Bug #14541]:     https://bugs.ruby-lang.org/issues/14541
[Feature #14722]: https://bugs.ruby-lang.org/issues/14722
[Bug #15409]:     https://bugs.ruby-lang.org/issues/15409
[Feature #15504]: https://bugs.ruby-lang.org/issues/15504
[Feature #15575]: https://bugs.ruby-lang.org/issues/15575
[Feature #15822]: https://bugs.ruby-lang.org/issues/15822
[Misc #15893]:    https://bugs.ruby-lang.org/issues/15893
[Feature #15921]: https://bugs.ruby-lang.org/issues/15921
[Feature #15973]: https://bugs.ruby-lang.org/issues/15973
[Feature #16131]: https://bugs.ruby-lang.org/issues/16131
[Feature #16150]: https://bugs.ruby-lang.org/issues/16150
[Feature #16166]: https://bugs.ruby-lang.org/issues/16166
[Feature #16175]: https://bugs.ruby-lang.org/issues/16175
[Feature #16233]: https://bugs.ruby-lang.org/issues/16233
[Feature #16260]: https://bugs.ruby-lang.org/issues/16260
[Feature #16274]: https://bugs.ruby-lang.org/issues/16274
[Feature #16345]: https://bugs.ruby-lang.org/issues/16345
[Feature #16377]: https://bugs.ruby-lang.org/issues/16377
[Feature #16378]: https://bugs.ruby-lang.org/issues/16378
[Feature #16555]: https://bugs.ruby-lang.org/issues/16555
[Feature #16604]: https://bugs.ruby-lang.org/issues/16604
[Feature #16614]: https://bugs.ruby-lang.org/issues/16614
[Feature #16686]: https://bugs.ruby-lang.org/issues/16686
[Feature #16746]: https://bugs.ruby-lang.org/issues/16746
[Feature #16754]: https://bugs.ruby-lang.org/issues/16754
[Feature #16786]: https://bugs.ruby-lang.org/issues/16786
[Feature #16792]: https://bugs.ruby-lang.org/issues/16792
[Feature #16815]: https://bugs.ruby-lang.org/issues/16815
[Feature #16828]: https://bugs.ruby-lang.org/issues/16828
[Misc #16961]:    https://bugs.ruby-lang.org/issues/16961
[Bug #17030]:     https://bugs.ruby-lang.org/issues/17030
[Feature #17055]: https://bugs.ruby-lang.org/issues/17055
[Feature #17104]: https://bugs.ruby-lang.org/issues/17104
[Feature #17122]: https://bugs.ruby-lang.org/issues/17122
[Feature #17136]: https://bugs.ruby-lang.org/issues/17136
[Feature #17176]: https://bugs.ruby-lang.org/issues/17176
[Feature #17187]: https://bugs.ruby-lang.org/issues/17187
[Bug #17221]:     https://bugs.ruby-lang.org/issues/17221
[Feature #17260]: https://bugs.ruby-lang.org/issues/17260
[Feature #17273]: https://bugs.ruby-lang.org/issues/17273
[Feature #17303]: https://bugs.ruby-lang.org/issues/17303
[Feature #17314]: https://bugs.ruby-lang.org/issues/17314
[Feature #17322]: https://bugs.ruby-lang.org/issues/17322
[Feature #17351]: https://bugs.ruby-lang.org/issues/17351
[Feature #17371]: https://bugs.ruby-lang.org/issues/17371
[Bug #17419]:     https://bugs.ruby-lang.org/issues/17419
[GH-2991]:        https://github.com/ruby/ruby/pull/2991

**Comment by eregon** [comment]
I'll start by importing the CRuby 3.0.2 files and report here when done.

**Comment by chrisseaton** [comment]
@wildmaples and I can handle keyword argument as part of our current work. Do you want to note that down to avoid conflict?

**Comment by eregon** [comment]
OK, I added you in the description for  keyword arguments-related changes.
That's probably the easiest way to keep track, but we could also use the wiki or a spreadsheet if that's more convenient.

**Comment by gogainda** [comment]
@eregon I would like to try some easy java task

**Comment by eregon** [comment]
@gogainda Then any task which is `easy` but not `pure ruby` should fall into that category.
You can just choose and mention it here.
Here is one I spotted from a quick look, feel free to pick that one or another:
> [easy] Module#alias_method now returns the defined alias as a symbol. [Feature #17314]

**Comment by gogainda** [comment]
@eregon thanks, lets assign it to myself then

**Comment by Strech** [comment]
Hey @eregon I've checked this one item `[easy, ruby-only] The following methods now return Array instances instead of
subclass instances when called on subclass instances:` and it seems that everything is already working for `3.x` as expected.

```console
$ for name in drop drop_while flatten slice element_reference take take_while uniq multiply; do PRETEND_RUBY_VERSION=3.0.2 bin/jt --use ruby test spec/ruby/core/array/$name\_spec.rb; done; echo "exit=$?"
...
...
...
exit=0
```

So I think it should be ticked as done.

**Comment by Strech** [comment]
If no one mind will take this one to check

> Warning
>
> [should already be the case, easy] Warning#warn now supports a category keyword argument.
> [Feature #17122]

**Comment by eregon** [comment]
Go ahead :)

**Comment by Strech** [comment]
Going to take a look into this one

> --help option
>
> [launcher, medium] When the environment variable RUBY_PAGER or PAGER is present and has
a non-empty value, and the standard input and output are tty, the --help
option shows the help message via the pager designated by the value.
[Feature #16754]

**Comment by rubyFeedback** [comment]
For ruby 3.1.0, I noticed that nobu changed time.rb a bit.

I do not know whether this affects truffleruby or not, but
one area that caused issues to my code base was the
removal of a constant aka RFC2822_DAY_NAME. That
constant just kept the weekdays in an array and I was
using that. With the removal I had to change a bit of
the downstream code.

I forgot which part it was (somewhere on github of ruby
is the applied change by nobu) but I wanted to mention
this in the event that it causes problems for other ruby
users if they depend on time-changes. Some things
got changed in MRI, so perhaps the above listing
by eregon should include any of the time-related
changes in ruby (I am not familiar what all changed ...
it was discussed on the ruby bug tracker, but I don't
remember it offhand right now).

**Comment by eregon** [comment]
@rubyFeedback We import `lib/time.rb` from CRuby, unchanged, so whatever change was done there we'll also have it, automatically.
If you'd like you can already file a short issue to ask for Ruby 3.1 support, but likely we won't get to it until 3.0 is done.

**Comment by eregon** [comment]
TruffleRuby now fully implements Ruby 3 keyword arguments since b8086afe6ecc64a78e1f80f42d4ae9c05cf56605 and that will be in the 22.1 release.

**Comment by ms-ati** [comment]
Just noting here that released TruffleRuby 22.0.0.2 reports itself as `RUBY_VERSION` of `3.0.2`, but it appears to not fully conform to the Ruby 3.0 behavior when passing a final `Hash` argument to a method taking both splat and double-splat arguments.

You can see a test that needs to check for TruffleRuby to workaround this behavior here:
https://github.com/ms-ati/docile/pull/90

**Comment by Strech** [comment]
@eregon I would like to try a medium-level difficulty issue

> [medium] yield in singleton class definitions in methods is now a SyntaxError
instead of a warning. yield in a class definition outside of a method
is now a SyntaxError instead of a LocalJumpError. [[Feature #15575](https://bugs.ruby-lang.org/issues/15575)]

**Comment by eregon** [comment]
Noted.

**Comment by Strech** [comment]
@eregon If you don't mind I will try to tackle this issue

> When a class variable is overtaken by the same definition in an
ancestor class/module, a RuntimeError is now raised (previously,
it only issued a warning in verbose mode).
[[Bug #14541](https://bugs.ruby-lang.org/issues/14541)]

**Comment by eregon** [comment]
@Strech Alright. Something to know about this, TruffleRuby did not have the warning and never implemented the "overtaking semantics" of class variables, because it's unreasonably slow and nobody wants those semantics anyway. An example of it is https://bugs.ruby-lang.org/issues/14541#note-31. So I'd suggest for this item to only raise if a class var is assigned at the top-level, and ignore anything overtaking-related.

**Comment by eregon** [comment]
Most of it is now done and was in the 22.0 release. I'll close this issue and we can address the remaining items when it becomes possible or important for compatibility.
