### ISSUE TITLE
Ruby 3.1 Support in TruffleRuby

### ISSUE THREAD

**Issue by fniephaus** [oracle/truffleruby#2733]
We are working on Ruby 3.1 support for the next release.

Any help is appreciated whether it is:
* implementing one of the Ruby 3.1 changes in TruffleRuby, and ensuring it is tested in specs or MRI tests and otherwise add specs
* adding specs for Ruby 3.1 changes, which is best done in ruby/spec directly, see https://github.com/ruby/spec/issues/923

To make it easier to find good getting-started issues, I annotated items with `easy`, `medium` and `hard`.
There is also `pure ruby` for changes which should only affect Ruby code and not require any change to Java sources or any Java knowledge.
If there is no `pure ruby` then some Java code is involved, but it should still be fairly straightforward if `easy` or `medium`.
`hard` typically requires more knowledge about TruffleRuby implementation details.

If you'd like to start on some task please mention it here or edit the description directly for committers (to avoid duplicated work).

# Full list of changes for Ruby 3.1.2

NOTE: https://rubyreferences.github.io/rubychanges/3.1.html gives more details for many features and changes. 

From https://github.com/ruby/ruby/blob/master/doc/NEWS/NEWS-3.1.0.md:

This document is a list of user-visible feature changes
since the **3.0.0** release, except for bug fixes.

Note that each entry is kept to a minimum, see links for details.

## Language changes

- [x] The block argument can now be anonymous if the block will
    only be passed to another method. [[Feature #11256]]

    ```ruby
    def foo(&)
      bar(&)
    end
    ```

- [ ] [hard, need pattern matching first] Pin operator now takes an expression. [[Feature #17411]]

    ```ruby
    Prime.each_cons(2).lazy.find_all{_1 in [n, ^(n + 2)]}.take(3).to_a
    #=> [[3, 5], [5, 7], [11, 13]]
    ```

- [ ] [hard, need pattern matching first] Pin operator now supports instance, class, and global variables.
    [[Feature #17724]]

    ```ruby
    @n = 5
    Prime.each_cons(2).lazy.find{_1 in [n, ^@n]}
    #=> [3, 5]
    ```

- [ ] [hard, need pattern matching first] One-line pattern matching is no longer experimental.

- [ ] [hard, need pattern matching first] Parentheses can be omitted in one-line pattern matching.
    [[Feature #16182]]

    ```ruby
    [0, 1] => _, x
    {y: 2} => y:
    x #=> 1
    y #=> 2
    ```

- [ ] [hard, java] Multiple assignment evaluation order has been made consistent with
    single assignment evaluation order.  With single assignment, Ruby
    uses a left-to-right evaluation order.  With this code:

    ```ruby
    foo[0] = bar
    ```

    The following evaluation order is used:

    1. `foo`
    2. `bar`
    3. `[]=` called on the result of `foo`

    In Ruby before 3.1.0, multiple assignment did not follow this
    evaluation order.  With this code:

    ```ruby
    foo[0], bar.baz = a, b
    ```

    Versions of Ruby before 3.1.0 would evaluate in the following
    order

    1. `a`
    2. `b`
    3. `foo`
    4. `[]=` called on the result of `foo`
    5. `bar`
    6. `baz=` called on the result of `bar`

    Starting in Ruby 3.1.0, the evaluation order is now consistent with
    single assignment, with the left-hand side being evaluated before
    the right-hand side:

    1. `foo`
    2. `bar`
    3. `a`
    4. `b`
    5. `[]=` called on the result of `foo`
    6. `baz=` called on the result of `bar`

    [[Bug #4443]]

- [x] Values in Hash literals and keyword arguments can be omitted.
    [[Feature #14579]]

    For example,

    * `{x:, y:}` is a syntax sugar of `{x: x, y: y}`.
    * `foo(x:, y:)` is a syntax sugar of `foo(x: x, y: y)`.

    Constant names, local variable names, and method names are allowed as
    key names.  Note that a reserved word is considered as a local
    variable or method name even if it's a pseudo variable name such as
    `self`.

- [ ] [hard, need Ractor first] Non main-Ractors can get instance variables (ivars) of classes/modules
    if ivars refer to shareable objects.
    [[Feature #17592]]

- [ ] [hard, parser] A command syntax is allowed in endless method definitions, i.e.,
    you can now write `def foo = puts "Hello"`.
    Note that `private def foo = puts "Hello"` does not parse.
    [[Feature #17398]]

## Command line options

- [x] `--disable-gems` is now explicitly declared as "just for debugging".
  Never use it in any real-world codebase.
  [[Feature #17684]]

## Core classes updates

Note: We're only listing outstanding class updates.

Array

- [x] (@andrykonchin) Array#intersect? is added. [[Feature #15198]]

Class

- [x]  (@andrykonchin) Class#subclasses, which returns an array of classes
        directly inheriting from the receiver, not
        including singleton classes. [[Feature #18273]]

  ```ruby
  class A; end
  class B < A; end
  class C < B; end
  class D < A; end
  A.subclasses    #=> [D, B]
  B.subclasses    #=> [C]
  C.subclasses    #=> []
  ```

Enumerable

- [x]   Enumerable#compact is added. [[Feature #17312]]

- [x] Enumerable#tally now accepts an optional hash to count. [[Feature #17744]]

- [x] @horakivo    [easy, pure ruby] Enumerable#each_cons and each_slice to return a receiver. [[GH-1509]]

  ```ruby
  [1, 2, 3].each_cons(2){}
  # 3.0 => nil
  # 3.1 => [1, 2, 3]

  [1, 2, 3].each_slice(2){}
  # 3.0 => nil
  # 3.1 => [1, 2, 3]
  ```

Enumerator::Lazy

- [x]   Enumerator::Lazy#compact is added. [[Feature #17312]]

File

- [x]   [easy, pure ruby] File.dirname now accepts an optional argument for the level to
        strip path components. [[Feature #12194]]

GC

- [x]   "GC.measure_total_time = true" enables the measurement of GC.
        Measurement can introduce overhead. It is enabled by default.
        GC.measure_total_time returns the current setting.
        GC.stat[:time] or GC.stat(:time) returns measured time
        in milli-seconds. [[[Feature #10917]]]

- [x]   GC.total_time returns measured time in nano-seconds. [[[Feature #10917]]]

Integer

- [x]   #2905 [easy, pure ruby] Integer.try_convert is added. [[Feature #15211]]

Kernel

- [x]   (@andrykonchin) Kernel#load now accepts a module as the second argument,
        and will load the file using the given module as the
        top-level module. [[Feature #6210]]

Marshal

- [x]   [medium, pure ruby] Marshal.load now accepts a `freeze: true` option.
        All returned objects are frozen except for `Class` and
        `Module` instances. Strings are deduplicated. [[Feature #18148]]

MatchData

- [x] @horakivo   [easy, pure ruby] MatchData#match is added [[Feature #18172]]

- [x] @horakivo   [easy, pure ruby] MatchData#match_length is added [[Feature #18172]]

Method / UnboundMethod

- [x]   Method#public?, Method#private?, Method#protected?,
        UnboundMethod#public?, UnboundMethod#private?,
        UnboundMethod#protected? have been added. [[Feature #11689]]

Module

- [ ]   [hard, java, to do after fixing `super`] Module#prepend now modifies the ancestor chain if the receiver
        already includes the argument. Module#prepend still does not
        modify the ancestor chain if the receiver has already prepended
        the argument. [[Bug #17423]]

- [x] @horakivo [medium, use SingleValueCastNode] Module#private, #public, #protected, and #module_function will
        now return their arguments.  If a single argument is given, it
        is returned. If no arguments are given, nil is returned.  If
        multiple arguments are given, they are returned as an array.
        [[Feature #12495]]

Process

- [x]   @horakivo [easy, pure ruby, should be an "undefined" method] Process.\_fork is added. This is a core method for fork(2).
        Do not call this method directly; it is called by existing
        fork methods: Kernel.#fork, Process.fork, and IO.popen("-").
        Application monitoring libraries can overwrite this method to
        hook fork events. [[Feature #17795]]

Struct

- [x] (won't do, would makes things slower, more complex, and the code be removed in 3.2) @eregon [easy, pure ruby] Passing only keyword arguments to Struct#initialize is warned.
        You need to use a Hash literal to set a Hash to a first member.
        [[Feature #16806]]

- [x] (@moste00) [easy, pure ruby] StructClass#keyword_init? is added [[Feature #18008]]

String

- [x]   @horakivo [easy, pure ruby] Update Unicode version to 13.0.0 [[Feature #17750]]
        and Emoji version to 13.0 [[Feature #18029]]

- [x]  (@andrykonchin) String#unpack and String#unpack1 now accept an `offset:` keyword
        argument to start the unpacking after an arbitrary number of bytes
        have been skipped. If `offset` is outside of the string bounds
        `ArgumentError` is raised. [[Feature #18254]]

Thread

- [x] @horakivo   [easy, java] Thread#native_thread_id is added. [[Feature #17853]]

Thread::Backtrace

- [x] [easy, pure ruby] Thread::Backtrace.limit, which returns the value to limit backtrace
        length set by `--backtrace-limit` command line option, is added.
        [[Feature #17479]]

Thread::Queue

- [x]   Thread::Queue.new now accepts an Enumerable of initial values.
        [[Feature #17327]]

Time

- [x]   [easy, pure ruby] Time.new now accepts optional `in:` keyword argument for the
        timezone, as well as `Time.at` and `Time.now`, so that is now
        you can omit minor arguments to `Time.new`. [[Feature #17485]]

  ```ruby
  Time.new(2021, 12, 25, in: "+07:00")
  #=> 2021-12-25 00:00:00 +0700
  ```

  At the same time, time component strings are converted to
  integers more strictly now.

  ```ruby
  Time.new(2021, 12, 25, "+07:30")
  #=> invalid value for Integer(): "+07:30" (ArgumentError)
  ```

  Ruby 3.0 or earlier returned probably unexpected result
  `2021-12-25 07:00:00`, not `2021-12-25 07:30:00` nor
  `2021-12-25 00:00:00 +07:30`.

- [x] (@andrykonchin)   Time#strftime supports RFC 3339 UTC for unknown offset local
        time, `-0000`, as `%-z`. [[Feature #17544]]

TracePoint

- [ ]   [medium, java] TracePoint.allow_reentry is added to allow reenter while TracePoint
        callback.
        [[Feature #15912]]

$LOAD_PATH

- [x] [medium, pure ruby, check if not already the case] $LOAD_PATH.resolve_feature_path does not raise. [[Feature #16043]]

Fiber Scheduler

- [ ]   [hard, need Fiber scheduler core first] Add support for `Addrinfo.getaddrinfo` using `address_resolve` hook.
        [[Feature #17370]]

- [ ]   [hard, need Fiber scheduler core first] Introduce non-blocking `Timeout.timeout` using `timeout_after` hook.
        [[Feature #17470]]

- [ ]   [hard, need Fiber scheduler core first] Introduce new scheduler hooks `io_read` and `io_write` along with a
        low level `IO::Buffer` for zero-copy read/write. [[Feature #18020]]

- [ ]   [hard, need Fiber scheduler core first] IO hooks `io_wait`, `io_read`, `io_write`, receive the original IO object
        where possible. [[Bug #18003]]

- [x]   Make `Monitor` fiber-safe. [[Bug #17827]]

- [x]   Replace copy coroutine with pthread implementation. [[Feature #18015]]

Refinement

- [x]   New class which represents a module created by Module#refine.
- [x]  @horakivo  [medium, pure ruby] `include` and `prepend` are deprecated, and `import_methods` is added
        instead. [[Bug #17429]]

## Stdlib updates

- [x] The following default gem are updated.
    * RubyGems 3.3.3
    * base64 0.1.1
    * benchmark 0.2.0
    * bigdecimal 3.1.1
    * bundler 2.3.3
    * cgi 0.3.1
    * csv 3.2.2
    * date 3.2.2
    * did_you_mean 1.6.1
    * digest 3.1.0
    * drb 2.1.0
    * erb 2.2.3
    * error_highlight 0.3.0
    * etc 1.3.0
    * fcntl 1.0.1
    * fiddle 1.1.0
    * fileutils 1.6.0
    * find 0.1.1
    * io-console 0.5.10
    * io-wait 0.2.1
    * ipaddr 1.2.3
    * irb 1.4.1
    * json 2.6.1
    * logger 1.5.0
    * net-http 0.2.0
    * net-protocol 0.1.2
    * nkf 0.1.1
    * open-uri 0.2.0
    * openssl 3.0.0
    * optparse 0.2.0
    * ostruct 0.5.2
    * pathname 0.2.0
    * pp 0.3.0
    * prettyprint 0.1.1
    * psych 4.0.3
    * racc 1.6.0
    * rdoc 6.4.0
    * readline 0.0.3
    * readline-ext 0.1.4
    * reline 0.3.0
    * resolv 0.2.1
    * rinda 0.1.1
    * ruby2_keywords 0.0.5
    * securerandom 0.1.1
    * set 1.0.2
    * stringio 3.0.1
    * strscan 3.0.1
    * tempfile 0.1.2
    * time 0.2.0
    * timeout 0.2.0
    * tmpdir 0.1.2
    * un 0.2.0
    * uri 0.11.0
    * yaml 0.2.0
    * zlib 2.1.1
- [x] The following bundled gems are updated.
    * minitest 5.15.0
    * power_assert 2.0.1
    * rake 13.0.6
    * test-unit 3.5.3
    * rexml 3.2.5
    * rbs 2.0.0
    * typeprof 0.21.1
- [x] The following default gems are now bundled gems.
    * net-ftp 0.1.3
    * net-imap 0.2.2
    * net-pop 0.1.1
    * net-smtp 0.3.1
    * matrix 0.4.2
    * prime 0.1.2
    * debug 1.4.0
- [x] The following gems has been removed from the Ruby standard library.
    * dbm
    * gdbm
    * tracer

- [ ] [hard, java] Coverage measurement now supports suspension. You can use `Coverage.suspend`
  to stop the measurement temporarily, and `Coverage.resume` to restart it.
  See [[Feature #18176]] in detail.

- [x] Random::Formatter is moved to random/formatter.rb, so that you can
  use `Random#hex`, `Random#base64`, and so on without SecureRandom.
  [[Feature #18190]]

## Compatibility issues

Note: Excluding feature bug fixes.

- [x] [note: they are not actually deprecated in headers] `rb_io_wait_readable`, `rb_io_wait_writable` and `rb_wait_for_single_fd` are
  deprecated in favour of `rb_io_maybe_wait_readable`,
  `rb_io_maybe_wait_writable` and `rb_io_maybe_wait` respectively.
  `rb_thread_wait_fd` and `rb_thread_fd_writable` are deprecated. [[Bug #18003]]
- [x] [easy, C] `rb_io_maybe_wait_readable`, `rb_io_maybe_wait_writable` and `rb_io_maybe_wait` are added.

## Stdlib compatibility issues

- [x] `ERB#initialize` warns `safe_level` and later arguments even without -w.
  [[Feature #14256]]

- [x] `lib/debug.rb` is replaced with `debug.gem`

- [x] `Kernel#pp` in `lib/pp.rb` uses the width of `IO#winsize` by default.
  This means that the output width is automatically changed depending on
  your terminal size. [[Feature #12913]]

- [x] Psych 4.0 changes `Psych.load` as `safe_load` by the default.
  You may need to use Psych 3.3.2 for migrating to this behavior.
  [[Bug #17866]]

## C API updates

- [x] Documented. [[GH-4815]]

- [x] (@moste00) [easy, C] `rb_gc_force_recycle` is deprecated and has been changed to a no-op.
  [[Feature #18290]]

## Implementation improvements

- [x] Inline cache mechanism is introduced for reading class variables.
  [[Feature #17763]]

- [x] `instance_eval` and `instance_exec` now only allocate a singleton class when
  required, avoiding extra objects and improving performance. [[GH-5146]]

- [x] The performance of `Struct` accessors is improved. [[GH-5131]]

- [x] `mandatory_only?` builtin special form to improve performance on
  builtin methods. [[GH-5112]]

- [x] Experimental feature Variable Width Allocation in the garbage collector.
  This feature is turned off by default and can be enabled by compiling Ruby
  with flag `USE_RVARGC=1` set. [[Feature #18045]] [[Feature #18239]]

## Debugger

- [x] A new debugger [debug.gem](https://github.com/ruby/debug) is bundled.
  debug.gem is a fast debugger implementation, and it provides many features
  like remote debugging, colorful REPL, IDE (VSCode) integration, and more.
  It replaces `lib/debug.rb` standard library.

- [x] `rdbg` command is also installed into `bin/` directory to start and control
  debugging execution.

## error_highlight

A built-in gem called error_highlight has been introduced.
It shows fine-grained error locations in the backtrace.

Example: `title = json[:article][:title]`

If `json` is nil, it shows:

```
$ ruby test.rb
test.rb:2:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)

title = json[:article][:title]
            ^^^^^^^^^^
```

If `json[:article]` returns nil, it shows:

```
$ ruby test.rb
test.rb:2:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)

title = json[:article][:title]
                      ^^^^^^^^
```

This feature is enabled by default.
You can disable it by using a command-line option `--disable-error_highlight`.
See [the repository](https://github.com/ruby/error_highlight) in detail.

- [ ] [hard, won't do because it depends on RubyVM, maybe we should remove the gem?] Investigate how to make it work, currently it's not loaded by default and requiring seems to have no effect.

## Miscellaneous changes

- [x] [easy, pure Ruby, need to update tool/import-mri-files.sh to copy this file] lib/objspace/trace.rb is added, which is a tool for tracing the object
  allocation. Just by requiring this file, tracing is started *immediately*.
  Just by `Kernel#p`, you can investigate where an object was created.
  Note that just requiring this file brings a large performance overhead.
  This is only for debugging purposes. Do not use this in production.
  [[Feature #17762]]

- [x] [easy, pure Ruby, need to update tool/import-mri-files.sh to copy this file] Reuse `ext/objspace/lib/objspace.rb` from CRuby

- [x] @eregon [easy, java] Now exceptions raised in finalizers will be printed to `STDERR`, unless
  `$VERBOSE` is `nil`.  [[Feature #17798]]

- [x] `ruby -run -e httpd` displays URLs to access.  [[Feature #17847]]

- [x] Add `ruby -run -e colorize` to colorize Ruby code using
  `IRB::Color.colorize_code`.

- [x] @eregon `fiber.so` is now required by default, so Fiber.current, transfer available by default.

[Bug #4443]:      https://bugs.ruby-lang.org/issues/4443
[Feature #6210]:  https://bugs.ruby-lang.org/issues/6210
[Feature #10917]: https://bugs.ruby-lang.org/issues/10917
[Feature #11256]: https://bugs.ruby-lang.org/issues/11256
[Feature #11689]: https://bugs.ruby-lang.org/issues/11689
[Feature #12194]: https://bugs.ruby-lang.org/issues/12194
[Feature #12495]: https://bugs.ruby-lang.org/issues/12495
[Feature #12913]: https://bugs.ruby-lang.org/issues/12913
[Feature #14256]: https://bugs.ruby-lang.org/issues/14256
[Feature #14579]: https://bugs.ruby-lang.org/issues/14579
[Feature #15198]: https://bugs.ruby-lang.org/issues/15198
[Feature #15211]: https://bugs.ruby-lang.org/issues/15211
[Feature #15912]: https://bugs.ruby-lang.org/issues/15912
[Feature #16043]: https://bugs.ruby-lang.org/issues/16043
[Feature #16182]: https://bugs.ruby-lang.org/issues/16182
[Feature #16806]: https://bugs.ruby-lang.org/issues/16806
[Feature #17312]: https://bugs.ruby-lang.org/issues/17312
[Feature #17327]: https://bugs.ruby-lang.org/issues/17327
[Feature #17370]: https://bugs.ruby-lang.org/issues/17370
[Feature #17398]: https://bugs.ruby-lang.org/issues/17398
[Feature #17411]: https://bugs.ruby-lang.org/issues/17411
[Bug #17423]:     https://bugs.ruby-lang.org/issues/17423
[Bug #17429]:     https://bugs.ruby-lang.org/issues/17429
[Feature #17470]: https://bugs.ruby-lang.org/issues/17470
[Feature #17479]: https://bugs.ruby-lang.org/issues/17479
[Feature #17485]: https://bugs.ruby-lang.org/issues/17485
[Feature #17544]: https://bugs.ruby-lang.org/issues/17544
[Feature #17592]: https://bugs.ruby-lang.org/issues/17592
[Feature #17684]: https://bugs.ruby-lang.org/issues/17684
[Feature #17724]: https://bugs.ruby-lang.org/issues/17724
[Feature #17744]: https://bugs.ruby-lang.org/issues/17744
[Feature #17750]: https://bugs.ruby-lang.org/issues/17750
[Feature #17762]: https://bugs.ruby-lang.org/issues/17762
[Feature #17763]: https://bugs.ruby-lang.org/issues/17763
[Feature #17795]: https://bugs.ruby-lang.org/issues/17795
[Feature #17798]: https://bugs.ruby-lang.org/issues/17798
[Bug #17827]:     https://bugs.ruby-lang.org/issues/17827
[Feature #17847]: https://bugs.ruby-lang.org/issues/17847
[Feature #17853]: https://bugs.ruby-lang.org/issues/17853
[Bug #17866]:     https://bugs.ruby-lang.org/issues/17866
[Bug #18003]:     https://bugs.ruby-lang.org/issues/18003
[Feature #18008]: https://bugs.ruby-lang.org/issues/18008
[Feature #18015]: https://bugs.ruby-lang.org/issues/18015
[Feature #18020]: https://bugs.ruby-lang.org/issues/18020
[Feature #18029]: https://bugs.ruby-lang.org/issues/18029
[Feature #18045]: https://bugs.ruby-lang.org/issues/18045
[Feature #18148]: https://bugs.ruby-lang.org/issues/18148
[Feature #18172]: https://bugs.ruby-lang.org/issues/18172
[Feature #18176]: https://bugs.ruby-lang.org/issues/18176
[Feature #18190]: https://bugs.ruby-lang.org/issues/18190
[Feature #18229]: https://bugs.ruby-lang.org/issues/18229
[Feature #18239]: https://bugs.ruby-lang.org/issues/18239
[Feature #18254]: https://bugs.ruby-lang.org/issues/18254
[Feature #18273]: https://bugs.ruby-lang.org/issues/18273
[Feature #18290]: https://bugs.ruby-lang.org/issues/18290

[GH-1509]: https://github.com/ruby/ruby/pull/1509
[GH-4815]: https://github.com/ruby/ruby/pull/4815
[GH-5112]: https://github.com/ruby/ruby/pull/5112
[GH-5131]: https://github.com/ruby/ruby/pull/5131
[GH-5146]: https://github.com/ruby/ruby/pull/5146

**Comment by andrykonchin** [comment]
I've taken "Time.new now accepts optional in: keyword argument".

**Comment by andrykonchin** [comment]
I've taken "Enumerable#tally now accepts an optional hash to count"

**Comment by andrykonchin** [comment]
I've taken "$LOAD_PATH.resolve_feature_path does not raise"

**Comment by andrykonchin** [comment]
I've taken "Thread::Backtrace.limit"

**Comment by eregon** [comment]
Most of it is now done and will be in the 23.0 release. I'll close this issue and we can address the remaining items when it becomes possible or important for compatibility.
