### ISSUE TITLE
Ruby 3.3 support

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#3681]
We are working on Ruby 3.3 support for the next release (24.2).

Any help is appreciated whether it is:
* implementing one of the Ruby 3.3 changes in TruffleRuby, and ensuring it is tested in specs or MRI tests and otherwise add specs. If adding specs please leave a comment [here](https://github.com/ruby/spec/issues/1216) to mention you are working on adding these specs to avoid conflicts & duplicated work.
* adding specs for Ruby 3.3 changes, which is best done in ruby/spec directly, see https://github.com/ruby/spec/issues/1216

To make it easier to find good getting-started issues, I annotated items with `easy`, `medium` and `hard`.
There is also `pure ruby` for changes which should only affect Ruby code and not require any change to Java sources or any Java knowledge.
If there is no `pure ruby` then some Java code is involved, but it should still be fairly straightforward if `easy` or `medium`.
`hard` typically requires more knowledge about TruffleRuby implementation details.
`[import]` means this needs the import of Ruby 3.3 sources to happen first.

If you'd like to start on some task please mention it here or edit the description directly for committers (to avoid duplicated work).

# Full list of changes for Ruby 3.3.0

NOTE: https://rubyreferences.github.io/rubychanges/3.3.html gives more details for many features and changes. 

From https://github.com/ruby/ruby/blob/master/doc/NEWS/NEWS-3.3.0.md:

This document is a list of user-visible feature changes
since the **3.2.0** release, except for bug fixes.

Note that each entry is kept to a minimum, see links for details.

## Core classes updates

Note: We're only listing outstanding class updates.

Array

* [x] [easy, Java] @Th3-M4jor Array#pack now raises ArgumentError for unknown directives. [[Bug #19150]]. NOTE: change how unknown directives are handled in `org.truffleruby.core.format.pack.SimplePackParser#parse`. Fixes String#unpack as well.

Dir

* [x] (@andrykonchin) [medium, Ruby] Dir.for_fd added for returning a Dir object for the directory specified
      by the provided directory file descriptor. [[Feature #19347]]
* [x] (@andrykonchin) [medium, Ruby] Dir.fchdir added for changing the directory to the directory specified
      by the provided directory file descriptor. [[Feature #19347]]
* [x] (@andrykonchin) [easy, Ruby] Dir#chdir added for changing the directory to the directory specified by
      the provided `Dir` object. [[Feature #19347]]

Encoding

* [x] [easy, Ruby/Java]`Encoding#replicate` has been removed, it was already deprecated.  [[Feature #18949]]

Fiber

* [ ] Introduce Fiber#kill. [[Bug #595]]

```ruby
fiber = Fiber.new do
  while true
    puts "Yielding..."
    Fiber.yield
  end
ensure
  puts "Exiting..."
end

fiber.resume
# Yielding...
fiber.kill
# Exiting...
```

MatchData

* [x] [easy, Ruby] MatchData#named_captures now accepts optional `symbolize_names`
      keyword. [[Feature #19591]]

Module

* [x] (@andrykonchin) [medium, Java] Module#set_temporary_name added for setting a temporary name for a
      module. [[Feature #19521]]

ObjectSpace::WeakKeyMap

* [x] New core class to build collections with weak references.
      The class use equality semantic to lookup keys like a regular hash,
      but it doesn't hold strong references on the keys. [[Feature #18498]]

ObjectSpace::WeakMap

* [x] [easy, Java] ObjectSpace::WeakMap#delete was added to eagerly clear weak map
      entries. [[Feature #19561]]

Proc
* [x] [easy, Java] Now Proc#dup and Proc#clone call `#initialize_dup` and `#initialize_clone`
      hooks respectively.  [[Feature #19362]]

Process

* [x] New Process.warmup method that notify the Ruby virtual machine that the boot sequence is finished,
      and that now is a good time to optimize the application. This is useful
      for long-running applications. The actual optimizations performed are entirely
      implementation-specific and may change in the future without notice. [[Feature #18885]]

Process::Status

* WONTDO [easy, Ruby] Process::Status#& and Process::Status#>> are deprecated. [[Bug #19868]]

Range

* [x] (@andrykonchin) [medium, Ruby] Range#reverse_each can now process beginless ranges with an Integer endpoint. [[Feature #18515]]
* [x] (@andrykonchin) [easy, Ruby] Range#reverse_each now raises TypeError for endless ranges. [[Feature #18551]]
* [x] [easy, Ruby] Range#overlap? added for checking if two ranges overlap. [[Feature #19839]]

Refinement

* [x] [easy, Ruby] Add Refinement#target as an alternative of Refinement#refined_class.
      Refinement#refined_class is deprecated and will be removed in Ruby
      3.4.  [[Feature #19714]]

Regexp

* [x] The cache-based optimization now supports lookarounds and atomic groupings. That is, match
      for Regexp containing these extensions can now also be performed in linear time to the length
      of the input string. However, these cannot contain captures and cannot be nested. [[Feature #19725]]

String

* [x] [easy, Java] @Th3-M4jor String#unpack now raises ArgumentError for unknown directives. [[Bug #19150]]. NOTE: fixes Array#pack as well.
* [x] [medium, Ruby] String#bytesplice now accepts new arguments index/length or range of the
      source string to be copied.  [[Feature #19314]].

Thread::Queue

* [x] [easy, Ruby] Thread::Queue#freeze now raises TypeError. [[Bug #17146]]. NOTE: the Queue class is defined in `lib/truffle/thread.rb` file.

Thread::SizedQueue

* [x] [easy, Ruby] Thread::SizedQueue#freeze now raises TypeError. [[Bug #17146]]. NOTE: the SizedQueue class is defined in `lib/truffle/thread.rb` file.

Time

* [x] (@andrykonchin ) [medium, Ruby] Time.new with a string argument became stricter. [[Bug #19293]]

```ruby
Time.new('2023-12-20')
#  no time information (ArgumentError)
```

TracePoint

* [ ] TracePoint supports `rescue` event. When the raised exception was rescued,
      the TracePoint will fire the hook. `rescue` event only supports Ruby-level
      `rescue`. [[Feature #19572]]

## Stdlib updates

* [x] RubyGems and Bundler warn if users do `require` the following gems without adding them to Gemfile or gemspec.
  This is because they will become the bundled gems in the future version of Ruby. This warning is suppressed
  if you use bootsnap gem. We recommend to run your application with `DISABLE_BOOTSNAP=1` environmental variable
  at least once. This is limitation of this version.
  [[Feature #19351]] [[Feature #19776]] [[Feature #19843]]
    * abbrev
    * base64
    * bigdecimal
    * csv
    * drb
    * getoptlong
    * mutex_m
    * nkf
    * observer
    * racc
    * resolv-replace
    * rinda
    * syslog

* [x] (@andrykonchin) Socket#recv and Socket#recv_nonblock returns `nil` instead of an empty string on closed
  connections. Socket#recvmsg and Socket#recvmsg_nonblock returns `nil` instead of an empty packet on closed
  connections. [[Bug #19012]]

* [ ] Name resolution such as Socket.getaddrinfo, Socket.getnameinfo, Addrinfo.getaddrinfo, etc.
  can now be interrupted. [[Feature #19965]]

* [x] Random::Formatter#alphanumeric is extended to accept optional `chars`
  keyword argument. [[Feature #18183]]

* [x] The following default gem is added.

  * prism 0.19.0

* [x] The following default gems are updated.

  * RubyGems 3.5.3
  * abbrev 0.1.2
  * base64 0.2.0
  * benchmark 0.3.0
  * bigdecimal 3.1.5
  * bundler 2.5.3
  * cgi 0.4.1
  * csv 3.2.8
  * date 3.3.4
  * delegate 0.3.1
  * drb 2.2.0
  * english 0.8.0
  * erb 4.0.3
  * error_highlight 0.6.0
  * etc 1.4.3
  * fcntl 1.1.0
  * fiddle 1.1.2
  * fileutils 1.7.2
  * find 0.2.0
  * getoptlong 0.2.1
  * io-console 0.7.1
  * io-nonblock 0.3.0
  * io-wait 0.3.1
  * ipaddr 1.2.6
  * irb 1.11.0
  * json 2.7.1
  * logger 1.6.0
  * mutex_m 0.2.0
  * net-http 0.4.0
  * net-protocol 0.2.2
  * nkf 0.1.3
  * observer 0.1.2
  * open-uri 0.4.1
  * open3 0.2.1
  * openssl 3.2.0
  * optparse 0.4.0
  * ostruct 0.6.0
  * pathname 0.3.0
  * pp 0.5.0
  * prettyprint 0.2.0
  * pstore 0.1.3
  * psych 5.1.2
  * rdoc 6.6.2
  * readline 0.0.4
  * reline 0.4.1
  * resolv 0.3.0
  * rinda 0.2.0
  * securerandom 0.3.1
  * set 1.1.0
  * shellwords 0.2.0
  * singleton 0.2.0
  * stringio 3.1.0
  * strscan 3.0.7
  * syntax_suggest 2.0.0
  * syslog 0.1.2
  * tempfile 0.2.1
  * time 0.3.0
  * timeout 0.4.1
  * tmpdir 0.2.0
  * tsort 0.2.0
  * un 0.3.0
  * uri 0.13.0
  * weakref 0.1.3
  * win32ole 1.8.10
  * yaml 0.3.0
  * zlib 3.1.0

* [x] The following bundled gem is promoted from default gems.

  * racc 1.7.3

* [x] The following bundled gems are updated.

  * minitest 5.20.0
  * rake 13.1.0
  * test-unit 3.6.1
  * rexml 3.2.6
  * rss 0.3.0
  * net-ftp 0.3.3
  * net-imap 0.4.9
  * net-smtp 0.4.0
  * rbs 3.4.0
  * typeprof 0.21.9
  * debug 1.9.1

See GitHub releases like [Logger](https://github.com/ruby/logger/releases) or
changelog for details of the default gems or bundled gems.

### Prism

* [x] Introduced [the Prism parser](https://github.com/ruby/prism) as a default gem
    * Prism is a portable, error tolerant, and maintainable recursive descent parser for the Ruby language

## Compatibility issues

* WONTDO Subprocess creation/forking via the following file open methods is deprecated. [[Feature #19630]]
    * Kernel#open
    * URI.open
    * IO.binread
    * IO.foreach
    * IO.readlines
    * IO.read
    * IO.write

* [x] [easy, Java] When given a non-lambda, non-literal block, Kernel#lambda with now raises
  ArgumentError instead of returning it unmodified. These usages have been
  issuing warnings under the `Warning[:deprecated]` category since Ruby 3.0.0.
  [[Feature #19777]]

* [x] (@andrykonchin) [medium, Java] `it` calls without arguments in a block with no ordinary parameters are
  deprecated. `it` will be a reference to the first block parameter in Ruby 3.4.
  [[Feature #18980]]

* [x] (@rwstauner ) [easy, ~~Java~~ Ruby] Error message for NoMethodError have changed to not use the target object's `#inspect`
  for efficiency, and says "instance of ClassName" instead. [[Feature #18285]]

    ```ruby
    ([1] * 100).nonexisting
    # undefined method `nonexisting' for an instance of Array (NoMethodError)
    ```

* [x] [medium, Java] Now anonymous parameters forwarding is disallowed inside a block
  that uses anonymous parameters.  [[Feature #19370]]

## Stdlib compatibility issues

* [x] `racc` is promoted to bundled gems.
    * You need to add `racc` to your `Gemfile` if you use `racc` under bundler environment.
* [x] `ext/readline` is retired
    * We have `reline` that is pure Ruby implementation compatible with `ext/readline` API.
      We rely on `reline` in the future. If you need to use `ext/readline`, you can install
      `ext/readline` via rubygems.org with `gem install readline-ext`.
    * We no longer need to install libraries like `libreadline` or `libedit`.

## C API updates

`rb_postponed_job` updates
  * New APIs and deprecated APIs (see comments for details)
    * [ ] added: `rb_postponed_job_preregister()`
    * [ ] added: `rb_postponed_job_trigger()`
    * [x] deprecated: `rb_postponed_job_register()` (and semantic change. see below)
    * [x] deprecated: `rb_postponed_job_register_one()`
  * [x] The postponed job APIs have been changed to address some rare crashes.
    To solve the issue, we introduced new two APIs and deprecated current APIs.
    The semantics of these functions have also changed slightly; `rb_postponed_job_register`
    now behaves like the `once` variant in that multiple calls with the same
    `func` might be coalesced into a single execution of the `func`
    [[Feature #20057]]

Some updates for internal thread event hook APIs
  * [ ] `rb_internal_thread_event_data_t` with a target Ruby thread (VALUE)
    and callback functions (`rb_internal_thread_event_callback`) receive it.
    https://github.com/ruby/ruby/pull/8885
  * The following functions are introduced to manipulate Ruby thread local data
    from internal thread event hook APIs (they are introduced since Ruby 3.2).
    https://github.com/ruby/ruby/pull/8936
    * [ ] `rb_internal_thread_specific_key_create()`
    * [ ] `rb_internal_thread_specific_get()`
    * [ ] `rb_internal_thread_specific_set()`

* [ ] `rb_profile_thread_frames()` is introduced to get a frames from
  a specific thread.
  [[Feature #10602]]

* [x] (@andrykonchin) `rb_data_define()` is introduced to define `Data`. [[Feature #19757]]

* [ ] `rb_ext_resolve_symbol()` is introduced to search a function from
  extension libraries. [[Feature #20005]]

IO related updates:
  * [x] The details of `rb_io_t` will be hidden and deprecated attributes
    are added for each members. [[Feature #19057]]
  * [x] `rb_io_path(VALUE io)` is introduced to get a path of `io`.
  * [x] (@andrykochin) `rb_io_closed_p(VALUE io)` to get opening or closing of `io`.
  * [x] `rb_io_mode(VALUE io)` to get the mode of `io`.
  * [x] (@andrykochin) `rb_io_open_descriptor()` is introduced to make an IO object from a file
    descriptor.

[Bug #595]:       https://bugs.ruby-lang.org/issues/595
[Feature #10602]: https://bugs.ruby-lang.org/issues/10602
[Bug #17146]:     https://bugs.ruby-lang.org/issues/17146
[Feature #18183]: https://bugs.ruby-lang.org/issues/18183
[Feature #18285]: https://bugs.ruby-lang.org/issues/18285
[Feature #18498]: https://bugs.ruby-lang.org/issues/18498
[Feature #18515]: https://bugs.ruby-lang.org/issues/18515
[Feature #18551]: https://bugs.ruby-lang.org/issues/18551
[Feature #18885]: https://bugs.ruby-lang.org/issues/18885
[Feature #18949]: https://bugs.ruby-lang.org/issues/18949
[Feature #18980]: https://bugs.ruby-lang.org/issues/18980
[Bug #19012]:     https://bugs.ruby-lang.org/issues/19012
[Feature #19057]: https://bugs.ruby-lang.org/issues/19057
[Bug #19150]:     https://bugs.ruby-lang.org/issues/19150
[Bug #19293]:     https://bugs.ruby-lang.org/issues/19293
[Feature #19314]: https://bugs.ruby-lang.org/issues/19314
[Feature #19347]: https://bugs.ruby-lang.org/issues/19347
[Feature #19351]: https://bugs.ruby-lang.org/issues/19351
[Feature #19362]: https://bugs.ruby-lang.org/issues/19362
[Feature #19370]: https://bugs.ruby-lang.org/issues/19370
[Feature #19521]: https://bugs.ruby-lang.org/issues/19521
[Feature #19538]: https://bugs.ruby-lang.org/issues/19538
[Feature #19561]: https://bugs.ruby-lang.org/issues/19561
[Feature #19571]: https://bugs.ruby-lang.org/issues/19571
[Feature #19572]: https://bugs.ruby-lang.org/issues/19572
[Feature #19591]: https://bugs.ruby-lang.org/issues/19591
[Feature #19630]: https://bugs.ruby-lang.org/issues/19630
[Feature #19637]: https://bugs.ruby-lang.org/issues/19637
[Feature #19678]: https://bugs.ruby-lang.org/issues/19678
[Feature #19714]: https://bugs.ruby-lang.org/issues/19714
[Feature #19725]: https://bugs.ruby-lang.org/issues/19725
[Feature #19757]: https://bugs.ruby-lang.org/issues/19757
[Feature #19776]: https://bugs.ruby-lang.org/issues/19776
[Feature #19777]: https://bugs.ruby-lang.org/issues/19777
[Feature #19785]: https://bugs.ruby-lang.org/issues/19785
[Feature #19790]: https://bugs.ruby-lang.org/issues/19790
[Feature #19839]: https://bugs.ruby-lang.org/issues/19839
[Feature #19842]: https://bugs.ruby-lang.org/issues/19842
[Feature #19843]: https://bugs.ruby-lang.org/issues/19843
[Bug #19868]:     https://bugs.ruby-lang.org/issues/19868
[Feature #19965]: https://bugs.ruby-lang.org/issues/19965
[Feature #20005]: https://bugs.ruby-lang.org/issues/20005
[Feature #20057]: https://bugs.ruby-lang.org/issues/20057

**Comment by andrykonchin** [comment]
Working on

> [medium, Java] `it` calls without arguments in a block with no ordinary parameters are
>   deprecated. `it` will be a reference to the first block parameter in Ruby 3.4.
>   [[Feature #18980]]

**Comment by Th3-M4jor** [comment]
I will take on this one
> [easy, Java] Array#pack now raises ArgumentError for unknown directives. [[Bug #19150](https://bugs.ruby-lang.org/issues/19150)]. NOTE: change how unknown directives are handled in org.truffleruby.core.format.pack.SimplePackParser#parse. Fixes String#unpack as well.

**Comment by andrykonchin** [comment]
Will work on

> Now anonymous parameters forwarding is disallowed inside a block
> that uses anonymous parameters. [[Feature #19370](https://bugs.ruby-lang.org/issues/19370)]

**Comment by andrykonchin** [comment]
Working on 
> Range#reverse_each can now process beginless ranges with an Integer endpoint. [[Feature #18515](https://bugs.ruby-lang.org/issues/18515)]

**Comment by andrykonchin** [comment]
Will work on 
> String#bytesplice now accepts new arguments index/length or range of the
> source string to be copied. [[Feature #19314](https://bugs.ruby-lang.org/issues/19314)].

**Comment by Th3-M4jor** [comment]
Working on

> Thread::Queue#freeze now raises TypeError. [[Bug #17146](https://bugs.ruby-lang.org/issues/17146)]. NOTE: the Queue class is defined in lib/truffle/thread.rb file.

> Thread::SizedQueue#freeze now raises TypeError. [[Bug #17146](https://bugs.ruby-lang.org/issues/17146)]. NOTE: the SizedQueue class is defined in lib/truffle/thread.rb file.

**Comment by andrykonchin** [comment]
Working on 

> Time.new with a string argument became stricter. [[Bug #19293](https://bugs.ruby-lang.org/issues/19293)]

**Comment by andrykonchin** [comment]
Working on

>[medium, Ruby] Dir.for_fd added for returning a Dir object for the directory specified
> by the provided directory file descriptor. [[Feature #19347](https://bugs.ruby-lang.org/issues/19347)]
> [medium, Ruby] Dir.fchdir added for changing the directory to the directory specified
> by the provided directory file descriptor. [[Feature #19347](https://bugs.ruby-lang.org/issues/19347)]
> [easy, Ruby] Dir#chdir added for changing the directory to the directory specified by
> the provided Dir object. [[Feature #19347](https://bugs.ruby-lang.org/issues/19347)]

**Comment by andrykonchin** [comment]
Working on

> Module#set_temporary_name added for setting a temporary name for a
module. [[Feature #19521](https://bugs.ruby-lang.org/issues/19521)]

**Comment by rwstauner** [comment]
I'll take
> [easy, Ruby/Java]Encoding#replicate has been removed, it was already deprecated. [[Feature #18949](https://bugs.ruby-lang.org/issues/18949)]

**Comment by rwstauner** [comment]
Working on
> [easy, Ruby] MatchData#named_captures now accepts optional symbolize_names
keyword. [[Feature #19591](https://bugs.ruby-lang.org/issues/19591)]

**Comment by rwstauner** [comment]
Working on
> [easy, Java] Now Proc#dup and Proc#clone call #initialize_dup and #initialize_clone
hooks respectively. [[Feature #19362](https://bugs.ruby-lang.org/issues/19362)]

**Comment by rwstauner** [comment]
I can do 
> [easy, Java] Error message for NoMethodError have changed to not use the target object's #inspect
for efficiency, and says "instance of ClassName" instead. [[Feature #18285](https://bugs.ruby-lang.org/issues/18285)]

though it looks to me like it can be done in Ruby

**Comment by andrykonchin** [comment]
Working on
> Socket#recv and Socket#recv_nonblock returns nil instead of an empty string on closed
connections. Socket#recvmsg and Socket#recvmsg_nonblock returns nil instead of an empty packet on closed
connections. [[Bug #19012](https://bugs.ruby-lang.org/issues/19012)]

**Comment by andrykonchin** [comment]
Working on
> rb_data_define() is introduced to define Data.

**Comment by Th3-M4jor** [comment]
Working on

> [easy, Java] When given a non-lambda, non-literal block, Kernel#lambda with now raises
ArgumentError instead of returning it unmodified. These usages have been
issuing warnings under the Warning[:deprecated] category since Ruby 3.0.0.
[[Feature #19777](https://bugs.ruby-lang.org/issues/19777)]

**Comment by andrykonchin** [comment]
Working on

> ObjectSpace::WeakMap#delete was added to eagerly clear weak map
entries. [[Feature #19561](https://bugs.ruby-lang.org/issues/19561)]

**Comment by eregon** [comment]
Closing this, basically all done, the remaining items either do no make sense on TruffleRuby or are low priority and will be addressed when a need for them arises.
